
export const AFF: Record<
  string,
  { icon: string; image: string; href: string }
> = {
  insulation: { icon: "🧱", image: "/catalog-categories/insulation.jpeg",        href: "https://roma.rs/fasadni-i-termoizolacioni-radovi/" },
  windows:    { icon: "🪟", image: "/catalog-categories/windows.jpeg",           href: "https://www.alumil.com/serbia/homeowners" },
  flooring:   { icon: "🪵", image: "/catalog-categories/parquet.jpeg",           href: "https://galerijapodova.com/" },
  lighting:   { icon: "💡", image: "/catalog-categories/lighting.jpeg",          href: "https://www.ikea.com/rs/sr/cat/rasveta-li001/" },
  bathroom:   { icon: "🛁", image: "/catalog-categories/bathroom-furniture.jpeg", href: "https://www.enmongroup.com/" },
  kitchen:    { icon: "🍳", image: "/catalog-categories/kitchen.jpeg",           href: "https://www.ikea.com/rs/sr/cat/kuhinjski-sistemi-ka003/" },
  furniture:  { icon: "🛋️", image: "/catalog-categories/bathroom-furniture.jpeg", href: "https://www.ikea.com/rs/sr/cat/namestaj-fu001/" },
  tools:      { icon: "🔧", image: "/catalog-categories/tools.jpeg",             href: "https://www.prodavnicaalata.rs/" },
  roofing:    { icon: "🏚️", image: "/catalog-categories/roofing.jpeg",           href: "https://www.wienerberger.rs/krov.html" },
  garden:     { icon: "🌿", image: "/catalog-categories/lawn.jpeg",              href: "https://gardencentar.rs/" },
  solar:      { icon: "☀️", image: "/catalog-categories/electrical.jpeg",        href: "https://www.solarenverde.rs/" },
  heating:    { icon: "🔥", image: "/catalog-categories/heating.jpeg",           href: "https://toplipod.rs/" },
  septic:     { icon: "💧", image: "/catalog-categories/septic.jpeg",            href: "https://prodock.rs/" },
  fence:      { icon: "🚧", image: "/catalog-categories/fence.jpeg",             href: "https://example.com/affiliate/fence/" },
  paint:      { icon: "🎨", image: "/catalog-categories/paint.jpeg",             href: "https://www.okov.rs/sr/boje-i-lakovi/boje-i-lakovi" },
};

/* Task→affiliate mapping */
export const TASK_AFF = {
  foundations:   ["tools","insulation"],
  walls:         ["insulation","tools"],
  roof:          ["roofing","tools"],
  installations: ["heating","lighting"],
  finishing:     ["flooring","lighting","paint"],
  fullbuild:     ["insulation","windows","roofing","flooring","heating"],
  ufh:           ["heating","flooring"],
  winreplace:    ["windows"],
  flooring:      ["flooring"],
  bathreno:      ["bathroom"],
  electrical:    ["lighting"],
  plumbing:      ["bathroom"],
  insulation:    ["insulation"],
  fullreno:      ["insulation","windows","flooring","bathroom","lighting"],
  furniture:     ["furniture"],
  kitchen:       ["kitchen"],
  bathequip:     ["bathroom"],
  lighting:      ["lighting"],
  decor:         ["furniture","lighting"],
  leveling:      ["tools"],
  lawn:          ["garden"],
  irrigation:    ["garden"],
  fence:         ["fence"],
  gate:          ["fence"],
  paths:         ["tools","garden"],
  outdoorlight:  ["lighting","garden"],
};
