import type { Lang } from "../translations";
import type { ProjectType } from "../types/plan";
import type { PlannerTaskType } from "./taskFormConfig";

export type PlannerParentCategoryId = ProjectType;
export type ConditionalStep = "details" | "infrastructure";
export type ConditionalFieldKind = "text" | "number" | "select" | "toggle";
export type ConditionalFieldSource = "parent-common" | "shared" | "task-specific";

export type ConditionalLocalizedText = Record<Lang, string>;

export type ConditionalFieldOption = {
  value: string;
  label: ConditionalLocalizedText;
};

export type ConditionalFieldDefinition = {
  id: string;
  key: string;
  canonicalKey: string;
  step: ConditionalStep;
  kind: ConditionalFieldKind;
  source: ConditionalFieldSource;
  importance: "required" | "optional";
  label: ConditionalLocalizedText;
  helper?: ConditionalLocalizedText;
  unknownAllowed?: boolean;
  options?: ConditionalFieldOption[];
};

export type ConditionalTaskDefinition = {
  id: string;
  parentId: PlannerParentCategoryId;
  label: ConditionalLocalizedText;
  detailFieldIds: string[];
  infrastructureFieldIds: string[];
  taskFormTaskKey?: PlannerTaskType;
};

export type ConditionalParentCategoryDefinition = {
  id: PlannerParentCategoryId;
  label: ConditionalLocalizedText;
  taskIds: string[];
  commonDetailFieldIds: string[];
  commonInfrastructureFieldIds: string[];
};

export const plannerFieldRegistry: Record<string, ConditionalFieldDefinition> = {
  propertyType: {
    id: "propertyType",
    key: "propertyType",
    canonicalKey: "propertyType",
    step: "details",
    kind: "select",
    source: "parent-common",
    importance: "required",
    label: { sr: "Tip objekta", en: "Property type", ru: "Tip obekta" },
    options: [
      { value: "apartment", label: { sr: "Stan", en: "Apartment", ru: "Kvartira" } },
      { value: "house", label: { sr: "Kuca", en: "House", ru: "Dom" } },
    ],
  },
  budgetBand: {
    id: "budgetBand",
    key: "budgetBand",
    canonicalKey: "budgetBand",
    step: "details",
    kind: "select",
    source: "parent-common",
    importance: "optional",
    label: { sr: "Okvirni budzet", en: "Approximate budget", ru: "Primerniy byudzhet" },
    options: [
      { value: "low", label: { sr: "Nizi", en: "Lower", ru: "Nizkiy" } },
      { value: "mid", label: { sr: "Srednji", en: "Middle", ru: "Sredniy" } },
      { value: "high", label: { sr: "Visi", en: "Higher", ru: "Vysokiy" } },
    ],
  },
  totalPropertyAreaM2: {
    id: "totalPropertyAreaM2",
    key: "totalPropertyAreaM2",
    canonicalKey: "totalPropertyAreaM2",
    step: "details",
    kind: "number",
    source: "shared",
    importance: "required",
    unknownAllowed: true,
    label: {
      sr: "Ukupna kvadratura objekta (m2)",
      en: "Total property area (m2)",
      ru: "Obshchaya ploshchad obekta (m2)",
    },
    helper: {
      sr: "Ako ne znate tacno, unesite okvirnu vrednost.",
      en: "If exact value is unknown, enter an approximate one.",
      ru: "Esli tochnaya velichina neizvestna, ukazhite primernuyu.",
    },
  },
  infraPowerAvailable: {
    id: "infraPowerAvailable",
    key: "infraPowerAvailable",
    canonicalKey: "infraPowerAvailable",
    step: "infrastructure",
    kind: "toggle",
    source: "parent-common",
    importance: "required",
    label: {
      sr: "Postoji dostupan prikljucak struje",
      en: "Power connection is available",
      ru: "Dostupno podklyuchenie elektroenergii",
    },
  },
  infraWaterAvailable: {
    id: "infraWaterAvailable",
    key: "infraWaterAvailable",
    canonicalKey: "infraWaterAvailable",
    step: "infrastructure",
    kind: "toggle",
    source: "parent-common",
    importance: "required",
    label: {
      sr: "Postoji dostupan prikljucak vode",
      en: "Water connection is available",
      ru: "Dostupno podklyuchenie vody",
    },
  },
  infraSewerAvailable: {
    id: "infraSewerAvailable",
    key: "infraSewerAvailable",
    canonicalKey: "infraSewerAvailable",
    step: "infrastructure",
    kind: "toggle",
    source: "parent-common",
    importance: "optional",
    label: {
      sr: "Postoji kanalizacioni prikljucak",
      en: "Sewer connection is available",
      ru: "Dostupno podklyuchenie k kanalizatsii",
    },
  },
  infraAccessForMachinery: {
    id: "infraAccessForMachinery",
    key: "infraAccessForMachinery",
    canonicalKey: "infraAccessForMachinery",
    step: "infrastructure",
    kind: "select",
    source: "shared",
    importance: "required",
    label: {
      sr: "Pristup mehanizaciji",
      en: "Machinery access",
      ru: "Dostup dlya tekhniki",
    },
    options: [
      { value: "easy", label: { sr: "Lako", en: "Easy", ru: "Legko" } },
      { value: "limited", label: { sr: "Ograniceno", en: "Limited", ru: "Ogranichenno" } },
      { value: "difficult", label: { sr: "Tesko", en: "Difficult", ru: "Slozhno" } },
    ],
  },
  infraExistingElectricalState: {
    id: "infraExistingElectricalState",
    key: "infraExistingElectricalState",
    canonicalKey: "infraExistingElectricalState",
    step: "infrastructure",
    kind: "select",
    source: "task-specific",
    importance: "optional",
    label: {
      sr: "Stanje postojece elektroinstalacije",
      en: "Existing electrical state",
      ru: "Sostoyanie suschestvuyuschey elektroseti",
    },
    options: [
      { value: "good", label: { sr: "Dobro", en: "Good", ru: "Khoroshee" } },
      { value: "partial", label: { sr: "Delimicno", en: "Partially functional", ru: "Chastichno" } },
      { value: "poor", label: { sr: "Lose", en: "Poor", ru: "Plokhoe" } },
    ],
  },
  infraExistingPlumbingState: {
    id: "infraExistingPlumbingState",
    key: "infraExistingPlumbingState",
    canonicalKey: "infraExistingPlumbingState",
    step: "infrastructure",
    kind: "select",
    source: "task-specific",
    importance: "optional",
    label: {
      sr: "Stanje postojece vodoinstalacije",
      en: "Existing plumbing state",
      ru: "Sostoyanie suschestvuyuschey santekhniki",
    },
    options: [
      { value: "good", label: { sr: "Dobro", en: "Good", ru: "Khoroshee" } },
      { value: "partial", label: { sr: "Delimicno", en: "Partially functional", ru: "Chastichno" } },
      { value: "poor", label: { sr: "Lose", en: "Poor", ru: "Plokhoe" } },
    ],
  },
  infraFacadeAccess: {
    id: "infraFacadeAccess",
    key: "infraFacadeAccess",
    canonicalKey: "infraFacadeAccess",
    step: "infrastructure",
    kind: "select",
    source: "task-specific",
    importance: "optional",
    label: {
      sr: "Pristup fasadi / otvorima",
      en: "Facade/openings access",
      ru: "Dostup k fasadu/proemam",
    },
    options: [
      { value: "ground", label: { sr: "Prizemlje", en: "Ground floor", ru: "Pervyy uroven" } },
      { value: "scaffold", label: { sr: "Potrebna skela", en: "Scaffold needed", ru: "Nuzhny lesa" } },
      { value: "rope", label: { sr: "Otezan pristup", en: "Difficult access", ru: "Slozhny dostup" } },
    ],
  },
  infraGateAutomationPower: {
    id: "infraGateAutomationPower",
    key: "infraGateAutomationPower",
    canonicalKey: "infraGateAutomationPower",
    step: "infrastructure",
    kind: "toggle",
    source: "task-specific",
    importance: "optional",
    label: {
      sr: "Postoji napajanje za automatiku kapije",
      en: "Power available for gate automation",
      ru: "Est pitaniye dlya avtomatiki vorot",
    },
  },
  yardLawnAreaM2: {
    id: "yardLawnAreaM2",
    key: "yardLawnAreaM2",
    canonicalKey: "yardLawnAreaM2",
    step: "details",
    kind: "number",
    source: "task-specific",
    importance: "required",
    unknownAllowed: true,
    label: {
      sr: "Povrsina travnjaka (m2)",
      en: "Lawn area (m2)",
      ru: "Ploshchad gazona (m2)",
    },
    helper: {
      sr: "Ako ne znate tacno, unesite okvirnu povrsinu.",
      en: "If exact value is unknown, enter an approximate area.",
      ru: "Esli tochnaya velichina neizvestna, vvedite primernuyu ploshchad.",
    },
  },
  yardLawnMethod: {
    id: "yardLawnMethod",
    key: "yardLawnMethod",
    canonicalKey: "yardLawnMethod",
    step: "details",
    kind: "select",
    source: "task-specific",
    importance: "required",
    label: {
      sr: "Tip travnjaka",
      en: "Lawn type",
      ru: "Tip gazona",
    },
    options: [
      { value: "seed", label: { sr: "Setva", en: "Seeding", ru: "Posev" } },
      { value: "turf", label: { sr: "Busen", en: "Turf", ru: "Rulonnyy" } },
    ],
  },
  yardGateWidthM: {
    id: "yardGateWidthM",
    key: "yardGateWidthM",
    canonicalKey: "yardGateWidthM",
    step: "details",
    kind: "number",
    source: "task-specific",
    importance: "required",
    unknownAllowed: true,
    label: {
      sr: "Sirina kapije (m)",
      en: "Gate width (m)",
      ru: "Shirina vorot (m)",
    },
  },
  yardGateMainType: {
    id: "yardGateMainType",
    key: "yardGateMainType",
    canonicalKey: "yardGateMainType",
    step: "details",
    kind: "select",
    source: "task-specific",
    importance: "required",
    label: {
      sr: "Tip kapije",
      en: "Gate type",
      ru: "Tip vorot",
    },
    options: [
      { value: "pedestrian", label: { sr: "Pesacka", en: "Pedestrian", ru: "Peshekhodnye" } },
      { value: "vehicle", label: { sr: "Kolna", en: "Vehicle", ru: "Avtomobilnye" } },
    ],
  },
  yardGateOpeningType: {
    id: "yardGateOpeningType",
    key: "yardGateOpeningType",
    canonicalKey: "yardGateOpeningType",
    step: "details",
    kind: "select",
    source: "task-specific",
    importance: "optional",
    label: {
      sr: "Nacin otvaranja",
      en: "Opening mechanism",
      ru: "Mekhanizm otkrytiya",
    },
    options: [
      { value: "sliding", label: { sr: "Klizna", en: "Sliding", ru: "Otkatnaya" } },
      { value: "swing", label: { sr: "Krilna", en: "Swing", ru: "Raspashnaya" } },
    ],
  },
  yardGateAutomation: {
    id: "yardGateAutomation",
    key: "yardGateAutomation",
    canonicalKey: "yardGateAutomation",
    step: "details",
    kind: "toggle",
    source: "task-specific",
    importance: "optional",
    label: {
      sr: "Automatska kapija",
      en: "Automatic gate",
      ru: "Avtomaticheskie vorota",
    },
  },
  yardOutdoorLightPointsCount: {
    id: "yardOutdoorLightPointsCount",
    key: "yardOutdoorLightPointsCount",
    canonicalKey: "yardOutdoorLightPointsCount",
    step: "details",
    kind: "number",
    source: "task-specific",
    importance: "required",
    unknownAllowed: true,
    label: {
      sr: "Broj svetlosnih tacaka",
      en: "Number of light points",
      ru: "Kolichestvo svetovykh tochek",
    },
  },
  yardOutdoorLightZonesCount: {
    id: "yardOutdoorLightZonesCount",
    key: "yardOutdoorLightZonesCount",
    canonicalKey: "yardOutdoorLightZonesCount",
    step: "details",
    kind: "number",
    source: "task-specific",
    importance: "optional",
    label: {
      sr: "Broj zona osvetljenja",
      en: "Number of lighting zones",
      ru: "Kolichestvo zon osveshcheniya",
    },
  },
  foundationType: {
    id: "foundationType",
    key: "foundationType",
    canonicalKey: "foundationType",
    step: "details",
    kind: "select",
    source: "task-specific",
    importance: "required",
    label: {
      sr: "Tip temelja",
      en: "Foundation type",
      ru: "Tip fundamenta",
    },
    options: [
      { value: "strip", label: { sr: "Trakasti", en: "Strip", ru: "Lentochnyy" } },
      { value: "slab", label: { sr: "Ploca", en: "Slab", ru: "Plita" } },
      { value: "pile", label: { sr: "Sipovi", en: "Piles", ru: "Svai" } },
    ],
  },
  wallPrimaryMaterial: {
    id: "wallPrimaryMaterial",
    key: "wallPrimaryMaterial",
    canonicalKey: "wallPrimaryMaterial",
    step: "details",
    kind: "select",
    source: "task-specific",
    importance: "required",
    label: {
      sr: "Primarni materijal zida",
      en: "Primary wall material",
      ru: "Osnovnoy material sten",
    },
    options: [
      { value: "brick", label: { sr: "Cigla", en: "Brick", ru: "Kirpich" } },
      { value: "block", label: { sr: "Blok", en: "Block", ru: "Blok" } },
      { value: "concrete", label: { sr: "Beton", en: "Concrete", ru: "Beton" } },
      { value: "wood", label: { sr: "Drvo", en: "Wood", ru: "Derevo" } },
    ],
  },
  roofStructureType: {
    id: "roofStructureType",
    key: "roofStructureType",
    canonicalKey: "roofStructureType",
    step: "details",
    kind: "select",
    source: "task-specific",
    importance: "required",
    label: {
      sr: "Krovna konstrukcija",
      en: "Roof structure",
      ru: "Konstruktsiya kryshi",
    },
    options: [
      { value: "wood", label: { sr: "Drvena", en: "Wooden", ru: "Derevyannaya" } },
      { value: "steel", label: { sr: "Celicna", en: "Steel", ru: "Stalnaya" } },
      { value: "flat", label: { sr: "Ravna ploca", en: "Flat slab", ru: "Ploskaya plita" } },
    ],
  },
  roofCoveringType: {
    id: "roofCoveringType",
    key: "roofCoveringType",
    canonicalKey: "roofCoveringType",
    step: "details",
    kind: "select",
    source: "task-specific",
    importance: "required",
    label: {
      sr: "Krovni pokrivac",
      en: "Roof covering",
      ru: "Krovelnoe pokrytie",
    },
    options: [
      { value: "tile", label: { sr: "Crep", en: "Tile", ru: "Cherepitsa" } },
      { value: "metal", label: { sr: "Lim", en: "Metal sheet", ru: "Metall" } },
      { value: "bitumen", label: { sr: "Bitumenski", en: "Bitumen", ru: "Bitumnyy" } },
    ],
  },
  yardLevelingAreaM2: {
    id: "yardLevelingAreaM2",
    key: "yardLevelingAreaM2",
    canonicalKey: "yardLevelingAreaM2",
    step: "details",
    kind: "number",
    source: "task-specific",
    importance: "required",
    label: {
      sr: "Povrsina nivelisanja (m2)",
      en: "Leveling area (m2)",
      ru: "Ploshchad planirovki (m2)",
    },
  },
  yardLevelingSlope: {
    id: "yardLevelingSlope",
    key: "yardLevelingSlope",
    canonicalKey: "yardLevelingSlope",
    step: "details",
    kind: "select",
    source: "task-specific",
    importance: "required",
    label: {
      sr: "Nagib terena",
      en: "Terrain slope",
      ru: "Uklon uchastka",
    },
    options: [
      { value: "flat", label: { sr: "Ravno", en: "Flat", ru: "Rovnyy" } },
      { value: "moderate", label: { sr: "Umeren", en: "Moderate", ru: "Umerennyy" } },
      { value: "steep", label: { sr: "Veliki nagib", en: "Steep", ru: "Krutoy" } },
    ],
  },
  yardIrrigationAreaM2: {
    id: "yardIrrigationAreaM2",
    key: "yardIrrigationAreaM2",
    canonicalKey: "yardIrrigationAreaM2",
    step: "details",
    kind: "number",
    source: "task-specific",
    importance: "required",
    label: {
      sr: "Povrsina navodnjavanja (m2)",
      en: "Irrigation area (m2)",
      ru: "Ploshchad orosheniya (m2)",
    },
  },
  yardIrrigationSystemType: {
    id: "yardIrrigationSystemType",
    key: "yardIrrigationSystemType",
    canonicalKey: "yardIrrigationSystemType",
    step: "details",
    kind: "select",
    source: "task-specific",
    importance: "required",
    label: {
      sr: "Tip sistema navodnjavanja",
      en: "Irrigation system type",
      ru: "Tip sistemy orosheniya",
    },
    options: [
      { value: "sprinkler", label: { sr: "Prskalice", en: "Sprinkler", ru: "Raspylenie" } },
      { value: "drip", label: { sr: "Kap po kap", en: "Drip", ru: "Kapelnyy" } },
      { value: "mixed", label: { sr: "Kombinovano", en: "Mixed", ru: "Smeshannyy" } },
    ],
  },
  yardFenceLengthM: {
    id: "yardFenceLengthM",
    key: "yardFenceLengthM",
    canonicalKey: "yardFenceLengthM",
    step: "details",
    kind: "number",
    source: "task-specific",
    importance: "required",
    label: {
      sr: "Duzina ograde (m)",
      en: "Fence length (m)",
      ru: "Dlina zabora (m)",
    },
  },
  yardFenceType: {
    id: "yardFenceType",
    key: "yardFenceType",
    canonicalKey: "yardFenceType",
    step: "details",
    kind: "select",
    source: "task-specific",
    importance: "required",
    label: {
      sr: "Tip ograde",
      en: "Fence type",
      ru: "Tip zabora",
    },
    options: [
      { value: "panel", label: { sr: "Panelna", en: "Panel", ru: "Panelnyy" } },
      { value: "wire", label: { sr: "Mrezasta", en: "Wire mesh", ru: "Setchatyy" } },
      { value: "masonry", label: { sr: "Zidana", en: "Masonry", ru: "Kamen/kladka" } },
      { value: "wood", label: { sr: "Drvena", en: "Wooden", ru: "Derevyannyy" } },
    ],
  },
  yardPathsAreaM2: {
    id: "yardPathsAreaM2",
    key: "yardPathsAreaM2",
    canonicalKey: "yardPathsAreaM2",
    step: "details",
    kind: "number",
    source: "task-specific",
    importance: "required",
    label: {
      sr: "Povrsina staza (m2)",
      en: "Path area (m2)",
      ru: "Ploshchad dorozhek (m2)",
    },
  },
  yardPathsSurfaceType: {
    id: "yardPathsSurfaceType",
    key: "yardPathsSurfaceType",
    canonicalKey: "yardPathsSurfaceType",
    step: "details",
    kind: "select",
    source: "task-specific",
    importance: "required",
    label: {
      sr: "Materijal staze",
      en: "Path surface material",
      ru: "Material dorozhki",
    },
    options: [
      { value: "concrete", label: { sr: "Beton", en: "Concrete", ru: "Beton" } },
      { value: "pavers", label: { sr: "Behaton", en: "Pavers", ru: "Bruschatka" } },
      { value: "stone", label: { sr: "Kamen", en: "Stone", ru: "Kamen" } },
      { value: "gravel", label: { sr: "Sljunak", en: "Gravel", ru: "Graviy" } },
    ],
  },
  installationsScopeType: {
    id: "installationsScopeType",
    key: "installationsScopeType",
    canonicalKey: "installationsScopeType",
    step: "details",
    kind: "select",
    source: "task-specific",
    importance: "required",
    label: {
      sr: "Obim instalacija",
      en: "Installation scope",
      ru: "Obem montazha kommunikatsiy",
    },
    options: [
      { value: "electrical", label: { sr: "Elektro", en: "Electrical", ru: "Elektro" } },
      { value: "plumbing", label: { sr: "Vodovod i kanalizacija", en: "Plumbing", ru: "Santekhnika" } },
      { value: "hvac", label: { sr: "Grejanje/hladjenje", en: "HVAC", ru: "Otoplenie/okhlazhdenie" } },
      { value: "full", label: { sr: "Kompletne instalacije", en: "Full package", ru: "Polnyy paket" } },
    ],
  },
  installationsElectricalPointsCount: {
    id: "installationsElectricalPointsCount",
    key: "installationsElectricalPointsCount",
    canonicalKey: "installationsElectricalPointsCount",
    step: "details",
    kind: "number",
    source: "task-specific",
    importance: "required",
    label: {
      sr: "Broj elektro tacaka",
      en: "Number of electrical points",
      ru: "Kolichestvo elektro tochek",
    },
    helper: {
      sr: "Ukljucite uticnice, prekidace i rasvetne izvode.",
      en: "Include outlets, switches, and light points.",
      ru: "Vklyuchite rozetki, vyklyuchateli i tochki osveshcheniya.",
    },
  },
  installationsPlumbingPointsCount: {
    id: "installationsPlumbingPointsCount",
    key: "installationsPlumbingPointsCount",
    canonicalKey: "installationsPlumbingPointsCount",
    step: "details",
    kind: "number",
    source: "task-specific",
    importance: "optional",
    label: {
      sr: "Broj vodovodnih tacaka",
      en: "Number of plumbing points",
      ru: "Kolichestvo santekhnicheskikh tochek",
    },
  },
  installationsEstimatedLengthM: {
    id: "installationsEstimatedLengthM",
    key: "installationsEstimatedLengthM",
    canonicalKey: "installationsEstimatedLengthM",
    step: "details",
    kind: "number",
    source: "task-specific",
    importance: "optional",
    label: {
      sr: "Procenjena duzina instalacija (m)",
      en: "Estimated installation length (m)",
      ru: "Primernaya dlina kommunikatsiy (m)",
    },
  },
  finishingLevel: {
    id: "finishingLevel",
    key: "finishingLevel",
    canonicalKey: "finishingLevel",
    step: "details",
    kind: "select",
    source: "task-specific",
    importance: "required",
    label: {
      sr: "Nivo zavrsne obrade",
      en: "Finishing level",
      ru: "Uroven otdelki",
    },
    options: [
      { value: "basic", label: { sr: "Osnovni", en: "Basic", ru: "Bazovyy" } },
      { value: "standard", label: { sr: "Standard", en: "Standard", ru: "Standart" } },
      { value: "premium", label: { sr: "Premium", en: "Premium", ru: "Premium" } },
    ],
  },
  finishingRoomsCount: {
    id: "finishingRoomsCount",
    key: "finishingRoomsCount",
    canonicalKey: "finishingRoomsCount",
    step: "details",
    kind: "number",
    source: "task-specific",
    importance: "required",
    label: {
      sr: "Broj prostorija za obradu",
      en: "Number of rooms to finish",
      ru: "Kolichestvo pomeshcheniy dlya otdelki",
    },
  },
  fullbuildFloorsCount: {
    id: "fullbuildFloorsCount",
    key: "fullbuildFloorsCount",
    canonicalKey: "fullbuildFloorsCount",
    step: "details",
    kind: "number",
    source: "task-specific",
    importance: "required",
    label: {
      sr: "Broj etaza",
      en: "Number of floors",
      ru: "Kolichestvo etazhey",
    },
  },
  fullbuildTargetStandard: {
    id: "fullbuildTargetStandard",
    key: "fullbuildTargetStandard",
    canonicalKey: "fullbuildTargetStandard",
    step: "details",
    kind: "select",
    source: "task-specific",
    importance: "required",
    label: {
      sr: "Ciljani nivo zavrsetka",
      en: "Target completion standard",
      ru: "Tselevoy uroven gotovnosti",
    },
    options: [
      { value: "rohbau", label: { sr: "Roh-bau", en: "Shell only", ru: "Korobka" } },
      { value: "semi", label: { sr: "Poluzavrseno", en: "Semi-finished", ru: "Chastichno gotov" } },
      { value: "turnkey", label: { sr: "Kljuc u ruke", en: "Turnkey", ru: "Pod klyuch" } },
    ],
  },
  furnitureRoomsCount: {
    id: "furnitureRoomsCount",
    key: "furnitureRoomsCount",
    canonicalKey: "furnitureRoomsCount",
    step: "details",
    kind: "number",
    source: "task-specific",
    importance: "required",
    label: {
      sr: "Broj prostorija za opremanje",
      en: "Number of rooms to furnish",
      ru: "Kolichestvo komnat dlya mebelirovki",
    },
  },
  furnitureType: {
    id: "furnitureType",
    key: "furnitureType",
    canonicalKey: "furnitureType",
    step: "details",
    kind: "select",
    source: "task-specific",
    importance: "required",
    label: {
      sr: "Tip namestaja",
      en: "Furniture type",
      ru: "Tip mebeli",
    },
    options: [
      { value: "modular", label: { sr: "Modularni", en: "Modular", ru: "Modulnyy" } },
      { value: "custom", label: { sr: "Po meri", en: "Custom made", ru: "Na zakaz" } },
      { value: "mixed", label: { sr: "Kombinovano", en: "Mixed", ru: "Smeshannyy" } },
    ],
  },
  kitchenLengthM: {
    id: "kitchenLengthM",
    key: "kitchenLengthM",
    canonicalKey: "kitchenLengthM",
    step: "details",
    kind: "number",
    source: "task-specific",
    importance: "required",
    label: {
      sr: "Duzina kuhinjskog niza (m)",
      en: "Kitchen run length (m)",
      ru: "Dlina kukhonnogo ryada (m)",
    },
  },
  kitchenLayoutType: {
    id: "kitchenLayoutType",
    key: "kitchenLayoutType",
    canonicalKey: "kitchenLayoutType",
    step: "details",
    kind: "select",
    source: "task-specific",
    importance: "required",
    label: {
      sr: "Raspored kuhinje",
      en: "Kitchen layout",
      ru: "Skhema kukhni",
    },
    options: [
      { value: "single", label: { sr: "Prava linija", en: "Single wall", ru: "Pryamaya" } },
      { value: "lshape", label: { sr: "L oblik", en: "L-shape", ru: "G-obraznaya" } },
      { value: "ushape", label: { sr: "U oblik", en: "U-shape", ru: "P-obraznaya" } },
      { value: "island", label: { sr: "Sa ostrvom", en: "With island", ru: "S ostrovom" } },
    ],
  },
  bathequipBathroomsCount: {
    id: "bathequipBathroomsCount",
    key: "bathequipBathroomsCount",
    canonicalKey: "bathequipBathroomsCount",
    step: "details",
    kind: "number",
    source: "task-specific",
    importance: "required",
    label: {
      sr: "Broj kupatila",
      en: "Number of bathrooms",
      ru: "Kolichestvo vannykh komnat",
    },
  },
  bathequipPackageLevel: {
    id: "bathequipPackageLevel",
    key: "bathequipPackageLevel",
    canonicalKey: "bathequipPackageLevel",
    step: "details",
    kind: "select",
    source: "task-specific",
    importance: "required",
    label: {
      sr: "Nivo opreme kupatila",
      en: "Bathroom equipment level",
      ru: "Uroven osnashcheniya vannoy",
    },
    options: [
      { value: "basic", label: { sr: "Osnovni", en: "Basic", ru: "Bazovyy" } },
      { value: "standard", label: { sr: "Standard", en: "Standard", ru: "Standart" } },
      { value: "premium", label: { sr: "Premium", en: "Premium", ru: "Premium" } },
    ],
  },
  lightingPointsCount: {
    id: "lightingPointsCount",
    key: "lightingPointsCount",
    canonicalKey: "lightingPointsCount",
    step: "details",
    kind: "number",
    source: "task-specific",
    importance: "required",
    label: {
      sr: "Broj rasvetnih tacaka",
      en: "Number of lighting points",
      ru: "Kolichestvo tochek osveshcheniya",
    },
  },
  lightingZonesCount: {
    id: "lightingZonesCount",
    key: "lightingZonesCount",
    canonicalKey: "lightingZonesCount",
    step: "details",
    kind: "number",
    source: "task-specific",
    importance: "optional",
    label: {
      sr: "Broj zona osvetljenja",
      en: "Number of lighting zones",
      ru: "Kolichestvo zon osveshcheniya",
    },
  },
  decorRoomsCount: {
    id: "decorRoomsCount",
    key: "decorRoomsCount",
    canonicalKey: "decorRoomsCount",
    step: "details",
    kind: "number",
    source: "task-specific",
    importance: "required",
    label: {
      sr: "Broj prostorija za dekoraciju",
      en: "Number of rooms for decoration",
      ru: "Kolichestvo komnat dlya dekora",
    },
  },
  decorStyleDirection: {
    id: "decorStyleDirection",
    key: "decorStyleDirection",
    canonicalKey: "decorStyleDirection",
    step: "details",
    kind: "select",
    source: "task-specific",
    importance: "optional",
    label: {
      sr: "Stilski pravac",
      en: "Style direction",
      ru: "Stilisticheskoe napravlenie",
    },
    options: [
      { value: "minimal", label: { sr: "Minimal", en: "Minimal", ru: "Minimalizm" } },
      { value: "modern", label: { sr: "Moderan", en: "Modern", ru: "Modern" } },
      { value: "classic", label: { sr: "Klasican", en: "Classic", ru: "Klassika" } },
      { value: "industrial", label: { sr: "Industrijski", en: "Industrial", ru: "Loft" } },
    ],
  },
};

export const plannerTaskDefinitions: Record<string, ConditionalTaskDefinition> = {
  foundations: {
    id: "foundations",
    parentId: "newbuild",
    label: { sr: "Temelji", en: "Foundations", ru: "Fundament" },
    detailFieldIds: ["totalPropertyAreaM2", "foundationType"],
    infrastructureFieldIds: ["infraAccessForMachinery"],
  },
  walls: {
    id: "walls",
    parentId: "newbuild",
    label: { sr: "Zidovi", en: "Walls", ru: "Steny" },
    detailFieldIds: ["totalPropertyAreaM2", "wallPrimaryMaterial"],
    infrastructureFieldIds: ["infraAccessForMachinery"],
  },
  roof: {
    id: "roof",
    parentId: "newbuild",
    label: { sr: "Krov", en: "Roof", ru: "Krovlya" },
    detailFieldIds: ["totalPropertyAreaM2", "roofStructureType", "roofCoveringType"],
    infrastructureFieldIds: ["infraAccessForMachinery"],
  },
  installations: {
    id: "installations",
    parentId: "newbuild",
    label: { sr: "Instalacije", en: "Installations", ru: "Kommunikatsii" },
    detailFieldIds: [
      "totalPropertyAreaM2",
      "installationsScopeType",
      "installationsElectricalPointsCount",
      "installationsPlumbingPointsCount",
      "installationsEstimatedLengthM",
    ],
    infrastructureFieldIds: ["infraPowerAvailable", "infraWaterAvailable", "infraSewerAvailable"],
  },
  finishing: {
    id: "finishing",
    parentId: "newbuild",
    label: { sr: "Zavrsni radovi", en: "Finishing works", ru: "Otdelochnye raboty" },
    detailFieldIds: ["totalPropertyAreaM2", "finishingLevel", "finishingRoomsCount"],
    infrastructureFieldIds: ["infraPowerAvailable", "infraWaterAvailable"],
  },
  fullbuild: {
    id: "fullbuild",
    parentId: "newbuild",
    label: { sr: "Kompletan objekat", en: "Complete building", ru: "Polnyy obekt" },
    detailFieldIds: ["totalPropertyAreaM2", "fullbuildFloorsCount", "fullbuildTargetStandard"],
    infrastructureFieldIds: ["infraPowerAvailable", "infraWaterAvailable", "infraSewerAvailable", "infraAccessForMachinery"],
  },
  ufh: {
    id: "ufh",
    parentId: "reno",
    label: { sr: "Podno grejanje", en: "Underfloor heating", ru: "Tepliy pol" },
    detailFieldIds: [],
    infrastructureFieldIds: ["infraPowerAvailable", "infraWaterAvailable"],
    taskFormTaskKey: "ufh",
  },
  winreplace: {
    id: "winreplace",
    parentId: "reno",
    label: { sr: "Zamena prozora", en: "Window replacement", ru: "Zamena okon" },
    detailFieldIds: [],
    infrastructureFieldIds: ["infraFacadeAccess"],
    taskFormTaskKey: "winreplace",
  },
  flooring: {
    id: "flooring",
    parentId: "reno",
    label: { sr: "Podne obloge", en: "Flooring", ru: "Napolnye pokrytiya" },
    detailFieldIds: [],
    infrastructureFieldIds: ["infraPowerAvailable"],
    taskFormTaskKey: "flooring",
  },
  bathreno: {
    id: "bathreno",
    parentId: "reno",
    label: { sr: "Renovacija kupatila", en: "Bathroom renovation", ru: "Remont vannoy" },
    detailFieldIds: [],
    infrastructureFieldIds: ["infraExistingPlumbingState", "infraExistingElectricalState", "infraWaterAvailable"],
    taskFormTaskKey: "bathreno",
  },
  electrical: {
    id: "electrical",
    parentId: "reno",
    label: { sr: "Elektroinstalacije", en: "Electrical works", ru: "Elektromontazh" },
    detailFieldIds: [],
    infrastructureFieldIds: ["infraExistingElectricalState", "infraPowerAvailable"],
    taskFormTaskKey: "electrical",
  },
  plumbing: {
    id: "plumbing",
    parentId: "reno",
    label: { sr: "Vodoinstalacije", en: "Plumbing works", ru: "Santekhnika" },
    detailFieldIds: [],
    infrastructureFieldIds: ["infraExistingPlumbingState", "infraWaterAvailable", "infraSewerAvailable"],
    taskFormTaskKey: "plumbing",
  },
  insulation: {
    id: "insulation",
    parentId: "reno",
    label: { sr: "Izolacija", en: "Insulation", ru: "Uteplenie" },
    detailFieldIds: [],
    infrastructureFieldIds: ["infraFacadeAccess"],
    taskFormTaskKey: "insulation",
  },
  fullreno: {
    id: "fullreno",
    parentId: "reno",
    label: { sr: "Kompletno renoviranje", en: "Full renovation", ru: "Polnyy remont" },
    detailFieldIds: ["totalPropertyAreaM2"],
    infrastructureFieldIds: ["infraPowerAvailable", "infraWaterAvailable", "infraSewerAvailable", "infraExistingElectricalState", "infraExistingPlumbingState"],
    taskFormTaskKey: "fullreno",
  },
  furniture: {
    id: "furniture",
    parentId: "interior",
    label: { sr: "Namestaj", en: "Furniture", ru: "Mebel" },
    detailFieldIds: ["furnitureRoomsCount", "furnitureType"],
    infrastructureFieldIds: [],
  },
  kitchen: {
    id: "kitchen",
    parentId: "interior",
    label: { sr: "Kuhinja", en: "Kitchen", ru: "Kukhnya" },
    detailFieldIds: ["kitchenLengthM", "kitchenLayoutType"],
    infrastructureFieldIds: ["infraPowerAvailable", "infraWaterAvailable", "infraSewerAvailable"],
  },
  bathequip: {
    id: "bathequip",
    parentId: "interior",
    label: { sr: "Kupatilska oprema", en: "Bathroom equipment", ru: "Vannoe oborudovanie" },
    detailFieldIds: ["bathequipBathroomsCount", "bathequipPackageLevel"],
    infrastructureFieldIds: ["infraPowerAvailable", "infraWaterAvailable", "infraSewerAvailable"],
  },
  lighting: {
    id: "lighting",
    parentId: "interior",
    label: { sr: "Osvetljenje", en: "Lighting", ru: "Osveshchenie" },
    detailFieldIds: ["lightingPointsCount", "lightingZonesCount"],
    infrastructureFieldIds: ["infraPowerAvailable", "infraExistingElectricalState"],
  },
  decor: {
    id: "decor",
    parentId: "interior",
    label: { sr: "Dekoracija", en: "Decoration", ru: "Dekor" },
    detailFieldIds: ["decorRoomsCount", "decorStyleDirection"],
    infrastructureFieldIds: [],
  },
  leveling: {
    id: "leveling",
    parentId: "yard",
    label: { sr: "Nivelisanje terena", en: "Site leveling", ru: "Planirovka uchastka" },
    detailFieldIds: ["yardLevelingAreaM2", "yardLevelingSlope"],
    infrastructureFieldIds: ["infraAccessForMachinery"],
  },
  lawn: {
    id: "lawn",
    parentId: "yard",
    label: { sr: "Travnjak", en: "Lawn", ru: "Gazonn" },
    detailFieldIds: ["yardLawnAreaM2", "yardLawnMethod"],
    infrastructureFieldIds: ["infraWaterAvailable"],
  },
  irrigation: {
    id: "irrigation",
    parentId: "yard",
    label: { sr: "Navodnjavanje", en: "Irrigation", ru: "Oroshenie" },
    detailFieldIds: ["yardIrrigationAreaM2", "yardIrrigationSystemType"],
    infrastructureFieldIds: ["infraWaterAvailable"],
  },
  fence: {
    id: "fence",
    parentId: "yard",
    label: { sr: "Ograda", en: "Fence", ru: "Zabor" },
    detailFieldIds: ["yardFenceLengthM", "yardFenceType"],
    infrastructureFieldIds: ["infraAccessForMachinery"],
  },
  gate: {
    id: "gate",
    parentId: "yard",
    label: { sr: "Kapija", en: "Gate", ru: "Vorota" },
    detailFieldIds: ["yardGateWidthM", "yardGateMainType", "yardGateOpeningType", "yardGateAutomation"],
    infrastructureFieldIds: ["infraGateAutomationPower", "infraPowerAvailable"],
  },
  paths: {
    id: "paths",
    parentId: "yard",
    label: { sr: "Staze i poplocavanje", en: "Paths and paving", ru: "Dorozhki i moshchenie" },
    detailFieldIds: ["yardPathsAreaM2", "yardPathsSurfaceType"],
    infrastructureFieldIds: ["infraAccessForMachinery"],
  },
  outdoorlight: {
    id: "outdoorlight",
    parentId: "yard",
    label: { sr: "Spoljasnje osvetljenje", en: "Outdoor lighting", ru: "Naruzhnoe osveshchenie" },
    detailFieldIds: ["yardOutdoorLightPointsCount", "yardOutdoorLightZonesCount"],
    infrastructureFieldIds: ["infraPowerAvailable"],
  },
};

export const plannerCategoriesConfig: Record<PlannerParentCategoryId, ConditionalParentCategoryDefinition> = {
  newbuild: {
    id: "newbuild",
    label: { sr: "Nova gradnja", en: "New build", ru: "Novoe stroitelstvo" },
    taskIds: ["foundations", "walls", "roof", "installations", "finishing", "fullbuild"],
    commonDetailFieldIds: ["propertyType", "budgetBand"],
    commonInfrastructureFieldIds: ["infraPowerAvailable", "infraWaterAvailable", "infraSewerAvailable", "infraAccessForMachinery"],
  },
  reno: {
    id: "reno",
    label: { sr: "Renoviranje", en: "Renovation", ru: "Remont" },
    taskIds: ["ufh", "winreplace", "flooring", "bathreno", "electrical", "plumbing", "insulation", "fullreno"],
    commonDetailFieldIds: ["propertyType", "budgetBand"],
    commonInfrastructureFieldIds: ["infraPowerAvailable", "infraWaterAvailable", "infraSewerAvailable"],
  },
  extension: {
    id: "extension",
    label: { sr: "Nadogradnja / dogradnja", en: "Extension", ru: "Nadstroika / pristroyka" },
    taskIds: ["foundations", "walls", "roof", "installations", "finishing", "fullbuild"],
    commonDetailFieldIds: ["propertyType", "budgetBand"],
    commonInfrastructureFieldIds: ["infraPowerAvailable", "infraWaterAvailable", "infraSewerAvailable", "infraAccessForMachinery"],
  },
  interior: {
    id: "interior",
    label: { sr: "Enterijer", en: "Interior", ru: "Interer" },
    taskIds: ["furniture", "kitchen", "bathequip", "lighting", "decor"],
    commonDetailFieldIds: ["propertyType", "budgetBand"],
    commonInfrastructureFieldIds: ["infraPowerAvailable"],
  },
  yard: {
    id: "yard",
    label: { sr: "Dvoriste", en: "Yard", ru: "Dvor" },
    taskIds: ["leveling", "lawn", "irrigation", "fence", "gate", "paths", "outdoorlight"],
    commonDetailFieldIds: ["budgetBand"],
    commonInfrastructureFieldIds: ["infraPowerAvailable", "infraWaterAvailable", "infraAccessForMachinery"],
  },
};
